/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import com.seaglasslookandfeel.SeaGlassLookAndFeel;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import logica.GestionCarrera;
import logica.GestionCorredor;
import modelo.Corredor;

/**
 *
 * @author alumnop
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    GestionCorredor gc = new GestionCorredor();
    GestionCarrera gca = new GestionCarrera();
    private static final String RUTA_LOGO = "/imgs/image1.png";

    /**
     * Creates new form PantallaPrincipalAltaCorredores
     *
     */
    public PantallaPrincipal() {
        initComponents();
        cambiarLookAndField();
        setIconImage(new ImageIcon(getClass().getResource(RUTA_LOGO)).getImage());
 
        UIManager.installLookAndFeel("seaglass",SeaGlassLookAndFeel.class.getCanonicalName());
    }

    public void cambiarLookAndField() {
        try {
            UIManager.setLookAndFeel(SeaGlassLookAndFeel.class.getCanonicalName());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Throwable e) {
            e.printStackTrace();
            JOptionPane.showConfirmDialog(this, "Error al establecer el look and feel");
        }
    }
    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonAnadirCorredor = new javax.swing.JButton();
        BotonVerCorredores = new javax.swing.JButton();
        BotonAnadirCarrera = new javax.swing.JButton();
        BotonVerCarreras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 460));

        BotonAnadirCorredor.setText("AÑDIR CORREDOR");
        BotonAnadirCorredor.setMaximumSize(new java.awt.Dimension(140, 25));
        BotonAnadirCorredor.setMinimumSize(new java.awt.Dimension(140, 25));
        BotonAnadirCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnadirCorredorActionPerformed(evt);
            }
        });

        BotonVerCorredores.setText("VER CORREDORES");
        BotonVerCorredores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerCorredoresActionPerformed(evt);
            }
        });

        BotonAnadirCarrera.setText("AÑADIR CARRERA");
        BotonAnadirCarrera.setMaximumSize(new java.awt.Dimension(140, 25));
        BotonAnadirCarrera.setMinimumSize(new java.awt.Dimension(140, 25));
        BotonAnadirCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnadirCarreraActionPerformed(evt);
            }
        });

        BotonVerCarreras.setText("VER CARRERAS");
        BotonVerCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerCarrerasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(BotonVerCorredores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(BotonAnadirCorredor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonAnadirCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(BotonVerCarreras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonVerCorredores, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonVerCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAnadirCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAnadirCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAnadirCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnadirCorredorActionPerformed
        AltaCorredores altaC = new AltaCorredores(this, true, gc);
        altaC.setVisible(true);


    }//GEN-LAST:event_BotonAnadirCorredorActionPerformed

    private void BotonVerCorredoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerCorredoresActionPerformed
        TablaCorredores tablaCorredores = new TablaCorredores(this, true, gc);
        tablaCorredores.setVisible(true);
    }//GEN-LAST:event_BotonVerCorredoresActionPerformed

    private void BotonAnadirCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnadirCarreraActionPerformed

        AltaCarreras altaCa = new AltaCarreras(this, true, gca);
        altaCa.setVisible(true);

    }//GEN-LAST:event_BotonAnadirCarreraActionPerformed

    private void BotonVerCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerCarrerasActionPerformed
        TablaCarreras tablaCarreras = new TablaCarreras(this, true, gca);
        tablaCarreras.setVisible(true);


    }//GEN-LAST:event_BotonVerCarrerasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAnadirCarrera;
    private javax.swing.JButton BotonAnadirCorredor;
    private javax.swing.JButton BotonVerCarreras;
    private javax.swing.JButton BotonVerCorredores;
    // End of variables declaration//GEN-END:variables
}
