/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import logica.GestionCarrera;
import logica.LogicaAplicacion;
import modelo.Carrera;
import modelo.Corredor;
import modelo.Resultado;
import modelo.TableModelCorredor;

/**
 *
 * @author inaki
 */
public class AltaCarreras extends javax.swing.JDialog {

    LogicaAplicacion la = new LogicaAplicacion();
    List listaParaTablePartipantes = new ArrayList();
    ArrayList<Resultado> listaCarrera = new ArrayList<>();
    int dorsal = 1;

    /**
     * Creates new form AltaCarreras
     *
     * @param parent
     * @param modal
     * @param la
     */
    public AltaCarreras(java.awt.Frame parent, boolean modal, LogicaAplicacion la, int index) {
        super(parent, modal);
        initComponents();
        this.la = la;
        TableModel tablaCorredores = new TableModelCorredor(la.getListaCorredores());
        jTableCorredores.setModel(tablaCorredores);

        if (index != -1) {

            Carrera c = la.getListaCarreras().get(index);
            jTextFieldNombre.setText(c.getNombre());
            jTextFieldLugar.setText(c.getLugar());
            jTextFieldNumeroMaxParticipantes.setText(String.valueOf(c.getNumeroMaxCorredores()));
            jSpinnerFecha.setValue(c.getFecha());

            ArrayList<Corredor> listaParticipantes = new ArrayList<>();
            for (Resultado corredorCarrera : c.getListaCarrera()) {
                Corredor corredorArray = corredorCarrera.getC();
                listaParticipantes.add(corredorArray);

            }
            
            for (Resultado listaResultado  : la.getListaCarreras().get(index).getListaCarrera()) {
                listaParaTablePartipantes.add(listaResultado.getC());
                listaCarrera.add(listaResultado);
                
            }
          
            TableModel tablaParticipantes = new TableModelCorredor(listaParaTablePartipantes);
            tablaParticipantes = new TableModelCorredor(listaParticipantes);
            jTableParticipantes.setModel(tablaParticipantes);
            
            la.getListaCarreras().remove(index);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabelNombre = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelLugar = new javax.swing.JLabel();
        jLabelParticipantes = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldLugar = new javax.swing.JTextField();
        jTextFieldNumeroMaxParticipantes = new javax.swing.JTextField();
        jSpinnerFecha = new javax.swing.JSpinner();
        jButtonValidar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableParticipantes = new javax.swing.JTable();
        jButtonAnadirCorredor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCorredores = new javax.swing.JTable();
        jButtonEliminarParticipante = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabelNombre.setText("Nombre:");

        jLabelFecha.setText("Fecha:");

        jLabelLugar.setText("Lugar:");

        jLabelParticipantes.setText("Nº Máx Participantes:");

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jTextFieldNumeroMaxParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroMaxParticipantesActionPerformed(evt);
            }
        });

        jSpinnerFecha.setModel(new javax.swing.SpinnerDateModel());

        jButtonValidar.setText("Validar");
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jTableParticipantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableParticipantes);

        jButtonAnadirCorredor.setText("Añadir Corredor");
        jButtonAnadirCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirCorredorActionPerformed(evt);
            }
        });

        jLabel1.setText("Lista Participantes");

        jTableCorredores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableCorredores);

        jButtonEliminarParticipante.setText("Eliminar Participante");
        jButtonEliminarParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarParticipanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButtonValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(42, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNombre)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelLugar)
                                        .addComponent(jLabelFecha))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelParticipantes)
                                        .addGap(2, 2, 2)))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSpinnerFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNumeroMaxParticipantes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                    .addComponent(jTextFieldLugar)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAnadirCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonEliminarParticipante)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombre)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFecha)
                            .addComponent(jSpinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLugar)
                            .addComponent(jTextFieldLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelParticipantes)
                            .addComponent(jTextFieldNumeroMaxParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAnadirCorredor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonLimpiar)
                            .addComponent(jButtonValidar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminarParticipante)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldNumeroMaxParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroMaxParticipantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroMaxParticipantesActionPerformed

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        // TODO add your handling code here:

        String nombre = jTextFieldNombre.getText();
        String lugar = jTextFieldLugar.getText();
        int numMaxCorredores = Integer.parseInt(jTextFieldNumeroMaxParticipantes.getText());
        Date fecha = (Date) jSpinnerFecha.getValue();
        Carrera ca = new Carrera(nombre, fecha, lugar, numMaxCorredores, listaCarrera, false);

        int resultado = JOptionPane.showConfirmDialog(this, "¿Quiere añadir esta carrera?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (resultado == JOptionPane.YES_OPTION) {

            JOptionPane.showMessageDialog(this, "Carrera añadida Correctamente", "Confirmación ", JOptionPane.INFORMATION_MESSAGE);
            la.getListaCarreras().add(ca);
        } else if (resultado == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "Carrera No añadida", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
        }

        this.dispose();
        System.out.println(la.getListaCarreras().toString());
        System.out.println(la.getListaCarreras().size());

    }//GEN-LAST:event_jButtonValidarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

        jTextFieldNombre.setText("");
        jTextFieldLugar.setText("");
        jTextFieldNumeroMaxParticipantes.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonAnadirCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirCorredorActionPerformed
        int index = jTableCorredores.getSelectedRow();
        
        if(jTextFieldNumeroMaxParticipantes.getText().equalsIgnoreCase(""))
            JOptionPane.showMessageDialog(this, "No ha seleccionado numero de participantes. Imposible añadir","Advertencia",JOptionPane.INFORMATION_MESSAGE);
        
        for (Resultado resultado : listaCarrera) {
            if(resultado.getC().equals(la.getListaCorredores().get(index)))
             JOptionPane.showMessageDialog(this, "El corredor ya está en la lista. Imposible añadir de nuevo","Advertencia",JOptionPane.INFORMATION_MESSAGE);
           return;
        }
        
        
        
        if (listaCarrera.size()>= Integer.parseInt(jTextFieldNumeroMaxParticipantes.getText())) {
             JOptionPane.showMessageDialog(this, "Número máximo de corredores alcanzado. Imposible añadir","Advertencia",JOptionPane.INFORMATION_MESSAGE);
        
        } else {

            Corredor c = la.getListaCorredores().get(index);
            Resultado r = new Resultado(c, dorsal, 0, 0);
            dorsal++;
            listaCarrera.add(r);
            listaParaTablePartipantes.add(c);
            TableModel tablaParticipantes = new TableModelCorredor(listaParaTablePartipantes);
            jTableParticipantes.setModel(tablaParticipantes);
        }
    }//GEN-LAST:event_jButtonAnadirCorredorActionPerformed

    private void jButtonEliminarParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarParticipanteActionPerformed
       if(jTableParticipantes.getSelectedRow()==-1)
         JOptionPane.showMessageDialog(this, "No ha seleccionado ningun participante, imposible eliminar","Advertencia",JOptionPane.INFORMATION_MESSAGE);
        else{
           listaCarrera.remove(jTableParticipantes.getSelectedRow());
           listaParaTablePartipantes.remove(jTableParticipantes.getSelectedRow());
           TableModel tablaParticipantes = new TableModelCorredor(listaParaTablePartipantes);
           jTableParticipantes.setModel(tablaParticipantes);
       }
    }//GEN-LAST:event_jButtonEliminarParticipanteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnadirCorredor;
    private javax.swing.JButton jButtonEliminarParticipante;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelLugar;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelParticipantes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinnerFecha;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableCorredores;
    private javax.swing.JTable jTableParticipantes;
    private javax.swing.JTextField jTextFieldLugar;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumeroMaxParticipantes;
    // End of variables declaration//GEN-END:variables
}
