/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Frame;
import javax.swing.JOptionPane;
import logica.LogicaAplicacion;
import modelo.Carrera;
import modelo.TableModelCarrera;

/**
 *
 * @author alumnop
 */
public class InicioCarreras extends javax.swing.JDialog {

    private LogicaAplicacion la = new LogicaAplicacion();
    private TableModelCarrera t;

    /**
     * Creates new form InicioCarreras
     *
     * @param parent
     * @param modal
     * @param la
     */
    public InicioCarreras(java.awt.Frame parent, boolean modal, LogicaAplicacion la) {
        super(parent, modal);
        initComponents();
        this.la = la;
        t = new TableModelCarrera(la.getListaCarreras());
        jTable1.setModel(t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonIniciarCarrera = new javax.swing.JButton();
        jButtonConsultarresultados = new javax.swing.JButton();
        jButtonNuevaCarrera = new javax.swing.JButton();
        jButtonGestion = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTIÓN CARRERAS");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonIniciarCarrera.setText("INICIAR CARRERA");
        jButtonIniciarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarCarreraActionPerformed(evt);
            }
        });

        jButtonConsultarresultados.setText("CONSULTAR RESULTADOS");
        jButtonConsultarresultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarresultadosActionPerformed(evt);
            }
        });

        jButtonNuevaCarrera.setText("NUEVA CARRERA");
        jButtonNuevaCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaCarreraActionPerformed(evt);
            }
        });

        jButtonGestion.setText("GESTIONAR CARRERA");
        jButtonGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNuevaCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jButtonGestion))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonIniciarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultarresultados, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevaCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jButtonIniciarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonConsultarresultados, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevaCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaCarreraActionPerformed
        AltaCarreras ac = new AltaCarreras((Frame) getParent(), true, la, -1);
        ac.setVisible(true);
        t = new TableModelCarrera(la.getListaCarreras());
        jTable1.setModel(t);
    }//GEN-LAST:event_jButtonNuevaCarreraActionPerformed

    private void jButtonGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionActionPerformed

        int index = jTable1.getSelectedRow();
        if(index ==-1){
         JOptionPane.showMessageDialog(this, "Imposible modificar carrera, no ha seleccionado ninguna","Advertencia",JOptionPane.INFORMATION_MESSAGE);
        }else{
            
        AltaCarreras ac = new AltaCarreras((Frame) getParent(), true, la, index);
        ac.setVisible(true);
        t = new TableModelCarrera(la.getListaCarreras());
        jTable1.setModel(t);
        }
    }//GEN-LAST:event_jButtonGestionActionPerformed

    private void jButtonIniciarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarCarreraActionPerformed
        int index = jTable1.getSelectedRow();
        if(index ==-1){
         JOptionPane.showMessageDialog(this, "Imposible iniciar carrera, no ha seleccionado ninguna","Advertencia",JOptionPane.INFORMATION_MESSAGE);
        }else if(la.getListaCarreras().get(index).isIsFinalizada()==true){
         JOptionPane.showMessageDialog(this, "La carrera ya se ha celebrado. Imposible iniciar de nuevo","Advertencia",JOptionPane.INFORMATION_MESSAGE); 
        }else{
        PantallaCarreras pc = new PantallaCarreras((Frame) getParent(), true, la, index);
        pc.setVisible(true);
        }
    }//GEN-LAST:event_jButtonIniciarCarreraActionPerformed

    private void jButtonConsultarresultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarresultadosActionPerformed
        int index = jTable1.getSelectedRow();
        Carrera c = la.getListaCarreras().get(index);
        if(index ==-1){
         JOptionPane.showMessageDialog(this, "Imposible consultar carrera, no ha seleccionado ninguna","Advertencia",JOptionPane.INFORMATION_MESSAGE);
        }else if(la.getListaCarreras().get(index).isIsFinalizada()==false)
         JOptionPane.showMessageDialog(this, "La carrera no se ha celebrado aún. Imposible ver los resultados","Advertencia",JOptionPane.INFORMATION_MESSAGE);   
        else{
        PantallaCarreras pc = new PantallaCarreras((Frame) getParent(), true, la, index);
        pc.setVisible(true);
        }
    }//GEN-LAST:event_jButtonConsultarresultadosActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarresultados;
    private javax.swing.JButton jButtonGestion;
    private javax.swing.JButton jButtonIniciarCarrera;
    private javax.swing.JButton jButtonNuevaCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
